export const mockData = [
    {
      id: 'g1',
      name: 'check_device_score',
      count: 123456,
      label: 'Event',
      rate: 0.97,
      status: 'S',
      childList: [
        {
          id: 'g12',
          name: '显示不全，鼠标移上来试试',
          count: 123456,
          label: 'xx元',
          rate: 0.123,
          status: 'S',
          childList: [
            {
              id: 'g121',
              name: '名称3',
              count: 123456,
              label: 'xx元',
              rate: 0.123,
              status: 'S',
              childList: [
                {
                  id: 'g1211',
                  name: '名称4',
                  count: 123456,
                  label: 'xx元',
                  rate: 0.123,
                  status: 'I',
                  childList: [],
                },
              ],
            },
            {
              id: 'g122',
              name: '名称5',
              count: 123456,
              label: 'xx元',
              rate: 0.96,
              status: 'S',
              childList: [
                {
                  id: 'g1221',
                  name: '名称6',
                  count: 123456,
                  label: 'xx元',
                  rate: 0.123,
                  status: 'S',
                  childList: [
                    {
                      id: 'g12211',
                      name: '名称6-1',
                      count: 123456,
                      label: 'xx元',
                      rate: 0.123,
                      status: 'I',
                      childList: [],
                    },
                  ],
                },
                {
                  id: 'g1222',
                  name: '名称7',
                  count: 123456,
                  label: 'xx元',
                  rate: 0.123,
                  status: 'S',
                  childList: [],
                },
              ],
            },
            {
              id: 'g123',
              name: '名称8',
              count: 123456,
              label: 'xx元',
              rate: 0.23,
              status: 'S',
              childList: [
                {
                  id: 'g1231',
                  name: '名称8-1',
                  count: 123456,
                  label: 'xx元',
                  rate: 0.123,
                  status: 'I',
                  childList: [],
                },
              ],
            },
          ],
        },
        {
          id: 'g13',
          name: '名称9',
          count: 123456,
          label: 'xx元',
          rate: 0.123,
          status: 'S',
          childList: [
            {
              id: 'g131',
              name: '名称10',
              count: 123456,
              label: 'xx元',
              rate: 0.123,
              status: 'I',
              childList: [],
            },
            {
              id: 'g132',
              name: '名称11',
              count: 123456,
              label: 'xx元',
              rate: 0.123,
              status: 'I',
              childList: [],
            },
          ],
        },
        {
          id: 'g14',
          name: '名称12',
          count: 123456,
          label: 'xx元',
          rate: 0.123,
          status: 'I',
          childList: [],
        },
      ],
    },
  ]